<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Nancys-MacBook-Air.local" failures="1" tests="7" name="Personal" time="0.028" errors="0" timestamp="2023-08-16T21:42:12 IST">
  <testcase classname="test.example.day1" name="test1" time="0.0"/>
  <testcase classname="test.example.day1" name="test4" time="0.0"/>
  <testcase classname="test.example.day1" name="test3" time="0.001"/>
  <testcase classname="test.example.day1" name="test5" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.example.day1.test5(day1.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase classname="test.example.day1" name="test2" time="0.0"/>
  <testcase classname="test.example.day1" name="test2" time="0.0"/>
  <testcase classname="test.example.day1" name="test2" time="0.001"/>
  <testcase classname="org.example.AppTest" name="newFeature" time="0.0">
    <ignored/>
  </testcase> <!-- newFeature -->
  <testcase classname="org.example.AppTest" name="fluentWait" time="0.0">
    <ignored/>
  </testcase> <!-- fluentWait -->
</testsuite> <!-- Personal -->
